# Generated by Django 5.0.6 on 2024-06-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_profile_age_profile_is_public_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.SmallIntegerField(blank=True),
        ),
    ]
